---
to: src/components/<%= Name %>/<%= Name %>.tsx
---
<%
    const Props = `${Name}Props`
-%>
import { FC } from 'react';

type <%= Props %> = {};

export const <%= Name %>: FC<<%= Props%>> = ({ }) => (
    <div>This is generated by hygen</div>
);
