---
to: src/components/<%= Name %>/<%= Name %>.test.tsx
---
import { render, screen } from '@testing-library/react';
import { <%= Name %> } from './<%= Name %>';

describe('<%= Name %>', () => {
    it('renders text', () => {
        render(<<%= Name %> />);
        expect(
            screen.queryByText('This is generated by hygen')
        ).toBeInTheDocument();
    });
});
