name: run-test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: 'yarn'
      - name: install dependencies
        run: yarn install --no-progress
      - name: lint
        run: yarn lint
      - name: type check
        run: yarn type-check
      - name: unit test
        run: yarn test:coverage
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
