name: run-test
on: [ pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: 'yarn'
      - name: install dependencies
        run: yarn install --no-progress
      - name: lint
        run: yarn lint
      - name: type check
        run: yarn type-check
      - name: unit test
        run: yarn test:coverage
      - name: Upload coverage report to Codecov
        run: codecov/codecov-action@v3
