name: run-test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.x"
      - name: install dependencies
        run: bun install --no-progress
      - name: lint
        run: bun run lint:all
      - name: type check
        run: bun run type-check
      - name: unit test only changed
        run: bun run test:coverage
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
