name: update npm packages
on: [pull_request]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: check outdated npm packages
        run: |
          echo 'outdated_report<<EOF' >> $GITHUB_ENV
          yarn outdated --json | npx -q -p yarn-outdated-formatter format-yarn-outdated --changelogs >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: upgrade npm packages
        run: yarn upgrade --latest
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: update outdated npm packages
          commit-message: update outdated npm packages
          branch: chore/update-outdated-packages-${{ steps.date.outputs.date }}
          delete-branch: true
          body: ${{ env.outdated_report}}
          assignees: t-yng
          reviewers: t-yng
