name: update npm packages
on:
  schedule:
    - cron: '00 10 10 * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: check outdated npm packages
        run: |
          echo 'outdated_report<<EOF' >> $GITHUB_ENV
          yarn outdated --json | npx -q -p yarn-outdated-formatter format-yarn-outdated --changelogs >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: upgrade npm packages
        run: yarn upgrade --latest
      - name: set env CURRENT_DATE
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: update outdated npm packages
          commit-message: update outdated npm packages
          branch: chore/update-outdated-packages-${{ env.CURRENT_DATE }}
          delete-branch: true
          body: ${{ env.outdated_report}}
          assignees: t-yng
          reviewers: t-yng
